name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
    paths-ignore:
      - 'docs/**'
      - 'documentation/**'
env:
  RUST_BACKTRACE: 1

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
        with:
          command: fmt
          args: --all -- --check
#
#  clippy:
#    name: Clippy
#    runs-on: ubuntu-latest
#    env:
#      RUSTFLAGS: -Dwarnings
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Install Rust
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
#          components: clippy
#
#      - name: Check examples
#        uses: actions-rs/cargo@v1
#        with:
#          command: clippy
#          args: --examples --all
#
#      - name: Check examples with all features on stable
#        uses: actions-rs/cargo@v1
#        with:
#          command: clippy
#          args: --examples --all-features --all
#
#      - name: Check benchmarks on nightly
#        uses: actions-rs/cargo@v1
#        with:
#          command: clippy
#          args: --all-features --examples --all --benches
